### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/vcsh-git#2]
GitLab is now my preferred project hosting platform, we'll use the current repository as a mirror instead

## Subtasks

* [ ] Import the project to GitLab(Currently blocked by service outage)
* [ ] Disable the Issues, Projects, and Wiki functionality of this project
* [ ] Update project metadata in GitHub
* [ ] Configure repository mirroring from GitLab to GitHub
